// Copyright 2024 Upbound Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// main package for the uptest tooling.
package main

import (
	"encoding/json"
	"log"
	"os"
	"syscall"

	"github.com/tufin/oasdiff/diff"
	"gopkg.in/alecthomas/kingpin.v2"
	"sigs.k8s.io/yaml"

	"github.com/upbound/uptest/pkg/crdschema"
)

var (
	app = kingpin.New("crddiff", "A tool for checking breaking API changes between two CRD OpenAPI v3 schemas. The schemas can come from either two revisions of a CRD, or from the versions declared in a single CRD.").DefaultEnvars()
	// crddiff sub-commands
	cmdRevision = app.Command("revision", "Compare the first schema available in a base CRD against the first schema from a revision CRD")
	cmdSelf     = app.Command("self", "Use OpenAPI v3 schemas from a single CRD")
)

var (
	revisionDiffOptions    = getCRDdiffCommonOptions(cmdRevision)
	selfDiffOptions        = getCRDdiffCommonOptions(cmdSelf)
	outputFormat           = app.Flag("output", "Output format: text, json, yaml").Default("text").Enum("text", "json", "yaml")
	revisionKeepAllChanges = cmdRevision.Flag("keep-all-changes", "Include all changes (breaking and non-breaking) in the output").Default("false").Bool()
	selfKeepAllChanges     = cmdSelf.Flag("keep-all-changes", "Include all changes (breaking and non-breaking) in the output").Default("false").Bool()
)

func getCRDdiffCommonOptions(cmd *kingpin.CmdClause) *crdschema.CommonOptions {
	opts := &crdschema.CommonOptions{}
	cmd.Flag("enable-upjet-extensions", "Enables diff extensions for the CRDs generated by upjet. "+
		"An example extension is the processing of the x-kubernetes-validations CEL rules generated by upjet.").Default("false").BoolVar(&opts.EnableUpjetExtensions)
	return opts
}

func main() {
	switch kingpin.MustParse(app.Parse(os.Args[1:])) {
	case cmdRevision.FullCommand():
		crdDiffRevision()
	case cmdSelf.FullCommand():
		crdDiffSelf()
	}
}

var (
	baseCRDPath     = cmdRevision.Arg("base", "The manifest file path of the CRD to be used as the base").Required().ExistingFile()
	revisionCRDPath = cmdRevision.Arg("revision", "The manifest file path of the CRD to be used as a revision to the base").Required().ExistingFile()
)

func crdDiffRevision() {
	crdDiff, err := crdschema.NewRevisionDiff(*baseCRDPath, *revisionCRDPath, crdschema.WithRevisionDiffCommonOptions(revisionDiffOptions))
	kingpin.FatalIfError(err, "Failed to load CRDs")
	reportDiff(crdDiff, *revisionKeepAllChanges)
}

var (
	crdPath = cmdSelf.Arg("crd", "The manifest file path of the CRD whose versions are to be checked for breaking changes").Required().ExistingFile()
)

func crdDiffSelf() {
	crdDiff, err := crdschema.NewSelfDiff(*crdPath, crdschema.WithSelfDiffCommonOptions(selfDiffOptions))
	kingpin.FatalIfError(err, "Failed to load CRDs")
	reportDiff(crdDiff, *selfKeepAllChanges)
}

func reportDiff(crdDiff crdschema.SchemaCheck, keepAllChanges bool) {
	switch *outputFormat {
	case "json":
		reportJSON(crdDiff, keepAllChanges)
	case "yaml":
		reportYAML(crdDiff, keepAllChanges)
	default:
		reportText(crdDiff, keepAllChanges)
	}
}

func reportText(crdDiff crdschema.SchemaCheck, keepAllChanges bool) {
	var versionMap map[string]*diff.Diff
	var err error
	if keepAllChanges {
		versionMap, err = crdDiff.GetRawDiff()
		kingpin.FatalIfError(err, "Failed to compute CRD breaking API changes")
	} else {
		versionMap, err = crdDiff.GetBreakingChanges()
		kingpin.FatalIfError(err, "Failed to compute CRD breaking API changes")
	}
	l := log.New(os.Stderr, "", 0)
	breakingDetected := false
	for v, d := range versionMap {
		if d.Empty() {
			continue
		}
		breakingDetected = true
		l.Printf("Version %q:\n", v)
		l.Println(crdschema.GetDiffReport(d))
	}
	if breakingDetected {
		syscall.Exit(1)
	}
}

func reportJSON(crdDiff crdschema.SchemaCheck, keepAllChanges bool) {
	rawDiff, err := crdDiff.GetRawDiff()
	kingpin.FatalIfError(err, "Failed to get schema changes")

	report, err := crdschema.GetChangesAsStructured(rawDiff, keepAllChanges)
	kingpin.FatalIfError(err, "Failed to get changes report")

	data, err := json.MarshalIndent(report, "", "  ")
	kingpin.FatalIfError(err, "Failed to marshal JSON")

	if _, err := os.Stdout.Write(data); err != nil {
		kingpin.FatalIfError(err, "Failed to write JSON")
	}
	if _, err := os.Stdout.WriteString("\n"); err != nil {
		kingpin.FatalIfError(err, "Failed to write JSON")
	}

	// Exit with error code if changes detected
	if !report.Empty() {
		syscall.Exit(1)
	}
}

func reportYAML(crdDiff crdschema.SchemaCheck, keepAllChanges bool) {
	rawDiff, err := crdDiff.GetRawDiff()
	kingpin.FatalIfError(err, "Failed to get schema changes")

	report, err := crdschema.GetChangesAsStructured(rawDiff, keepAllChanges)
	kingpin.FatalIfError(err, "Failed to get changes report")

	data, err := yaml.Marshal(report)
	kingpin.FatalIfError(err, "Failed to marshal YAML")

	if _, err := os.Stdout.Write(data); err != nil {
		kingpin.FatalIfError(err, "Failed to write YAML")
	}

	// Exit with error code if changes detected
	if !report.Empty() {
		syscall.Exit(1)
	}
}
